name = "RBTreeBenchmarkJulia"
uuid = "cc393383-1b94-4e67-b5e0-041cb4b0e18f"
authors = ["Pete Vilter <pete.vilter@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
